project_id = "uyqroiydexhdazxzrypd"

[functions.generate-product-sheet]
verify_jwt = false

[functions.sales-chat]
verify_jwt = false

[functions.create-wompi-checkout]
verify_jwt = false

[functions.verify-wompi-transaction]
verify_jwt = false